#Example1:
Dars1 = int(input("Nomre dars riazi khod ra wared konid:"))
Dars2 = int(input("Nomre dars oloom khod ra wared konid:"))
Dars3 = int(input("Nomre dars farsi khod ra wared konid:"))
Dars4 = int(input("Nomre dars arabi khod ra wared konid:"))
Dars5 = int(input("Nomre dars engelisi khod ra wared konid:"))
Dars6 = int(input("Nomre dars honar khod ra wared konid:"))
Dars7 = int(input("Nomre dars fizik khod ra wared konid:"))
Dars8 = int(input("Nomre dars shimi khod ra wared konid:"))
print(f"nomre dars riazi shoma: {Dars1}")
print(f"nomre dars oloom shoma: {Dars2}")
print(f"nomre dars farsi shoma: {Dars3}")
print(f"nomre dars arabi shoma: {Dars4}")
print(f"nomre dars engelisi shoma: {Dars5}")
print(f"nomre dars honar shoma: {Dars6}")
print(f"nomre dars fizik shoma: {Dars7}")
print(f"nomre dars shimi shoma: {Dars8}")

#Example2:
car1 = input("mashine aval khod ra wared konid:")
car2 = input("mashine dovom khod ra wared konid:")
car3 = input("mashine sevom khod ra wared konid:")
car4 = input("mashine chaharom khod ra wared konid:")
car5 = input("mashine panjom khod ra wared konid:")
car6 = input("mashine shishom khod ra wared konid:")
car7 = input("mashine haftom khod ra wared konid:")
car8 = input("mashine hashtom khod ra wared konid:")
print(f"mashine aval shoma: {car1}")
print(f"mashine dovom shoma: {car2}")
print(f"mashine sevom shoma: {car3}")
print(f"mashine chaharom shoma: {car4}")
print(f"mashine panjom shoma: {car5}")
print(f"mashine shishom shoma: {car6}")
print(f"mashine haftom shoma: {car7}")
print(f"mashine hashtom shoma: {car8}")